name: Merge

on:
  pull_request:
    types: [closed]

jobs:
  merged:
    if: (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Merged, thanks!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
